# render.yaml
services:
  - type: web
    name: stock-analysis-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "true"
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
